### ISSUE TITLE
Add consumerfinance.gov as featured repo

### ISSUE THREAD

**Issue by anselmbradford** [GSA/code-gov-web#118]
The three featured projects for CFPB are great and appreciated! But could we include https://github.com/cfpb/cfgov-refresh, the main consumerfinance.gov site, under which college costs and owning a home both live?
<img width="620" alt="screen shot 2016-11-03 at 7 52 56 pm" src="https://cloud.githubusercontent.com/assets/704760/19989767/2f204334-a1ff-11e6-9beb-692d80362ee2.png">

**Comment by anselmbradford** [comment]
Let me know if that repo needs any special formatting to be included or point me where to add a PR for including it. Thanks!

**Comment by okamanda** [comment]
Hi @anselmbradford Thanks for the tip. We'll included it in the next iteration. And we'll soon provide instructions for how to add repos more directly!

**Comment by DanielJDufour** [comment]
Closing.  Each agency manages their own code.json now.
