### ISSUE TITLE
URLs in repo description are not included

### ISSUE THREAD

**Issue by anselmbradford** [GSA/code-gov-web#121]
https://github.com/USDepartmentofLabor/Swift-Federal-Data-SDK includes a URL in the repo description, but that doesn't show up in https://code.gov/#/explore-code/agencies/DOL

<img width="704" alt="screen shot 2016-11-03 at 8 05 18 pm" src="https://cloud.githubusercontent.com/assets/704760/19990030/e173fe80-a200-11e6-8e3e-42941b8a3da9.png">

**Comment by bodnarbm** [comment]
The URL (http://usdepartmentoflabor.github.io/Swift-Federal-Data-SDK/) is not actually in the repo description. It is instead the listed homepage for the repo. Github displays this url immediately after the description, so it just looks like part of it.

This could be handled by displaying the homepage link after the description (similar to Github), but that would be true of all repos.

**Comment by lukad03** [comment]
This is an interesting issue - it touches on issues of norming around repo descriptions and on functionality provided by our API.

@bodnarbm Is right about links being included in each Repo page, but for repos that include links in the description we'll need to assess what level of risk we are willing to accept if we choose to enable these links. The alternative (and I believe this is the default functionality currently) is to remove links entirely, but then we're left with trailing sentences like the description you mentioned.

**Comment by anselmbradford** [comment]
@lukad03 possibly stripping out the href would be a happy median? Then it's not a clickable link but the text still makes sense.

**Comment by anselmbradford** [comment]
Though all the repositories linked would be theoretically trusted, right? Or something is very wrong.

**Comment by DanielJDufour** [comment]
Good conversation.  The current system is set up to display the description given by the agencies in their code.json.  Links will appear as plain text, so you won't be able to click on it.  Closing.
