### ISSUE TITLE
Add Explore Code order by programming language option.

### ISSUE THREAD

**Issue by spwilson2** [GSA/code-gov-web#140]
It'd be nice to be able to browse the list of featured projects in the explore-code section by programming language in case someone is looking to contribute to projects in a language they already know.

**Comment by bodnarbm** [comment]
I know I use a similar feature a lot with data.gov. Would be extremely helpful in the case of SDKs.

**Comment by srang** [comment]
This was exactly why I pulled up the project. I'm a java guy and its tough to look through each project to find one that fits my skillset. The other piece of this is that many of the language identifications are not quite right. Like a lot of the web projects are identified by CSS... It'd be great if the projects could specify core language or even framework on their quick listing in code.gov

**Comment by mcmahonjohn** [comment]
Another point is as GitHub showcases, some projects use a few languages/frameworks. So "java" or "javascript" may not be accurate enough. I recommend in addition to this request, more detailed info. If it's javascript, css, html, shell/bash, etc. That way more people are likely to find something of interest.

**Comment by DanielJDufour** [comment]
Thanks for the comments everyone.  We're about to archive this repo.  We rewrote code.gov and you can find the new repo here: https://github.com/GSA/code-gov-front-end

Hopefully, we also addressed your issues.  You can now filter by language: https://code.gov/browse-projects?&languages=Java&page=1&size=10&sort=data_quality

![image](https://user-images.githubusercontent.com/4313463/49472223-def0f800-f7dc-11e8-91fa-f86558e57e7c.png)

Feel free to open up new issues here https://github.com/GSA/code-gov-front-end
