### ISSUE TITLE
software.forge.mil migration

### ISSUE THREAD

**Issue by Dinsmoor** [GSA/code-gov-web#142]
Migrate existing free and open source software from software.forge.mil to code.gov, in light of the change from a free-software, free-for-use to a free-software, pay-for-use model.

Refer:
http://www.forge.mil/Community.html
https://software.forge.mil/

**Comment by okamanda** [comment]
Thanks!

**Comment by jbjonesjr** [comment]
@Dinsmoor are you asking how or where to migrate forge.mil projects to now that forge.mil is charging for all hosting? Or just clarifying that code.gov should have visibility to the projects hosted by forge.mil (even though they are currently hidden behind a CAC).

Anyone around here with experience with TeamForge, perhaps have a way to easily pull repository/project data similar to what is being done in [**@llnl/scraper**](https://github.com/llnl/scraper)? If not (or not possible), I wonder if the forge.mil team would be interested in taking on that task (or even reviewing their choice of version control tooling).

**Comment by IanLee1521** [comment]
Creator / maintainer of said [@llnl/scraper](https://github.com/llnl/scraper) tool here --

Not a user of TeamForge nor MilForge myself, though I was in the past, but I did just look at their documentation, and it looks like they also have a REST API that we would be able to add an interface for. In particular they have a "getProjects" endpoint that looks like it probably has (most of) the information that would be needed: https://forge.collab.net/apidoc/swagger/#!/Projects/getProjects

I would certainly welcome any contributions that wanted to add that functionality, and would be happy to work with anyone interested in creating it!

**Comment by Dinsmoor** [comment]
@jbjonesjr @IanLee1521 Sorry for delay, had research to do. Where and how are not so tough! :)

Where is easy; enabling code.gov (if running on apache2) to accept PKI certificates is pretty easy, and can be done with a download of the DoD CA + CRLs and a small change to the virtual host. It may be even better to just add a subdomain pki.code.gov for projects of that nature.

How is another question that would probably have to be talked out with the MilForge folks, as I can't even get my account unlocked to clone repositories anymore. Since they moved to a payment-required subscriber based model, I'm not sure how to *legally* clone repositories for hosting elsewhere as original unless the author moves it over, unless code.gov just wanted to make forks to be maintained separately from the parent codebase.

For those with a DoD CAC, I have a working example of GitLab at https://git.pki.pappad.info if the code.gov team wanted to see what an implementation could look like.

**Comment by DanielJDufour** [comment]
Hi, all.  Great suggestion, but AFAIK, it's the responsibility of the different agencies to create their own code.json files that list their open-source and government wide reuse repos.  Let us know if you'd like us to try to connect you with the open-source liaison for the respective agency. Welcome to reopen if necessary.
