### ISSUE TITLE
If code is produced in hackathons hosted by the federal government, does it belong here?

### ISSUE THREAD

**Issue by DCGenomics** [GSA/code-gov-web#188]

**Comment by DanielJDufour** [comment]
Hi, @DCGenomics , that's a great question.  We'd love to include this information, but the individual agencies hosting the hackathons will have to take lead on it.  Our current methodology is to harvest data provided by government agencies in their code.json file that they host.  Here's an example: https://www.justice.gov/code.json.

We're also exploring developing tools to facilitate management of hack events.  Open to your thoughts on what features/tools you'd like to see!

P.S. Big fan of DC Genomics Meetup! :-)

**Comment by DanielJDufour** [comment]
@DCGenomics , I'm closing this issue.  Feel free to create another issue if you have more questions, suggestions, or advice.  Thanks!
