### ISSUE TITLE
Submitting the EDGE Bioinformatics Repo.

### ISSUE THREAD

**Issue by joedanger** [GSA/code-gov-web#207]
Hey all, I've spent the last 4 years working on EDGE Bioinformatics, an open-source platform for genomics developed by the Naval Medical Research Center and Los Alamos National Laboratory.  We have a current repo available at: https://bitbucket.org/nmrcjoe/edge and docs at http://edge.readthedocs.io.

I see there's no DoD section so far, does anybody know what I have to do to submit the project to code.gov?

**Comment by DanielJDufour** [comment]
Hi, @joedanger .  I apologize for the late reply.  (I just started this month).  On the plus side, I see that EDGE has been included on code.gov . See https://code.gov/#/explore-code/agencies/DOE/repos/Edge%20Bioinformatics.

Closing issue.

**Comment by joedanger** [comment]
Sweet, obliged.
