### ISSUE TITLE
Run in production mode in production.

### ISSUE THREAD

**Issue by jmcarp** [GSA/code-gov-web#221]
Check out the note in the console:

<img width="965" alt="screen shot 2017-01-10 at 3 42 13 pm" src="https://cloud.githubusercontent.com/assets/1633460/21824009/7cde86cc-d74b-11e6-9177-a6466a2685c0.png">

I'm guessing you're not reaching this code: https://github.com/presidential-innovation-fellows/code-gov-web/blob/d92dd5e2f070b4b3496e842166b8c4ccf1e5a7f3/src/app/environment.ts#L16-L18

**Comment by okamanda** [comment]
@yozlet Can we track this down? Did you come across this when looking at the env variables?

**Comment by yozlet** [comment]
@okamanda Nope, that was a different issue on the server side.

**Comment by DanielJDufour** [comment]
This was fixed at https://github.com/GSA/code-gov-web/blob/master/src/app/environment.ts#L18
