### ISSUE TITLE
GitHub users: Topics as a way to classify your Repos

### ISSUE THREAD

**Issue by jbjonesjr** [GSA/code-gov-web#225]
👋 everyone! Today, GitHub released [TOPICS](https://t.co/JVJCj8JzeV), a new way to classify and organize your repository. This should hopefully be able to feed directly into the `tags` section of the code.gov schema going forward.

It will allow you to tag your repository with keywords (and the system will even suggest ones that it believes are relevant, based on your README and code contents). It provides auto-complete and normalizes the terms.

This will be coming to the API in the near future, so hopefully this will allow people to use even more native features of the tools (instead of retaining separate meta-data, and another asset to maintain).

* [help docs](https://help.github.com/articles/about-topics/)

**Comment by jbjonesjr** [comment]
For those of you itching to use GitHub Topics to store your project and repository tags, now you can! TOPICS (see previous message for details), is now available via the [API in preview](https://developer.github.com/v3/search/#search-repositories) (that means you have to include a specific user-agent to have access to it). However, it's stable and good to use.

If anyone is going to use this, i'd be interested in your feedback!

Thanks.

**Comment by okamanda** [comment]
@mattbailey0 @AlvandSalehi, shall we add to next schema version conversation?

**Comment by DanielJDufour** [comment]
I added topics to https://github.com/GSA/code-gov-front-end.  Thanks for the suggestion! :-)
