### ISSUE TITLE
Minor schema inconsistency with property names for URLs

### ISSUE THREAD

**Issue by iadgovuser1** [GSA/code-gov-web#241]
These are really minor, but I'm pointing them out for the sake of consistency:
- [project.]codeUrl versus [project.]downloadURL (e.g. Url versus URL)
- [project.]repository is a URL yet it doesn't have URL in its name
- [project.]license is a URL yet it doesn't have URL in its name
- [project.]homepage is a URL yet it doesn't have URL in its name

**Comment by DanielJDufour** [comment]
These are great comments.  I'm new on the project and AFAIK, they were integrated into the new schema.  Let us know if there's any other issues. Closing this now.
