### ISSUE TITLE
Update link to PDF

### ISSUE THREAD

**Issue by AlvandSalehi** [GSA/code-gov-web#254]
When a user clicks on "View PDF of Policy" on sourcecode.cio.gov, it fails to load the PDF. The link should be updated to the following: https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2016/m_16_21.pdf

**Comment by okamanda** [comment]
@AlvandSalehi, sourcecode.cio.gov is generated from a [https://github.com/WhiteHouse/source-code-policy](WhiteHouse github account: https://github.com/WhiteHouse/source-code-policy), so I think this request should be directed there. possible at @mattbailey0 ?

**Comment by PhilipBale** [comment]
https://github.com/WhiteHouse/source-code-policy/pull/269 @AlvandSalehi @okamanda @mattbailey0

**Comment by DanielJDufour** [comment]
I'm closing this issue do to inactivity.
