### ISSUE TITLE
Add USPTO Agency Artifacts

### ISSUE THREAD

**Issue by sashi-aeec** [GSA/code-gov-web#264]
Hi - We would like to list a few repositories from USPTO to code.gov. Could you please let us know how to go about this?  
 - Are we expected to manually edit repos.json file and submit a pull request? 
 - Should we provide you a list of our Github repos?

**Comment by okamanda** [comment]
@sashi-aeec USPTO is part of the Department of Commerce, right? Each federal agency is responsible for gathering its sub-agencies and organizations' repos and storing it in their code inventories (e.g., code.json). We gather that data daily and export a subset of those repos that we collect to the repos.json file that you see. 

So next steps would be to reach out to the code.gov point of contact for DOC. cc: @AlvandSalehi @PhilipBale 

In the meantime, can you share a link/list of your repos?

**Comment by sashi-aeec** [comment]
@AlvandSalehi @PhilipBale Could you please help us with this? One of the repositories we would like to add is here - [TrademarkStatusApp](https://github.com/USPTO/TrademarkStatusApp).
I'm gathering information about the other repository. 

Thanks

**Comment by PhilipBale** [comment]
Hey @sashi-aeec, I believe you need to reach out to the department of commerce point of contact to get your repositories listed.  They maintain the agency repository listings.  I'm working on finding out who that person is.

**Comment by jcastle** [comment]
This is true.  Current DoC rep is Rajeev Sharma.
