### ISSUE TITLE
Add element for Disclaimer text

### ISSUE THREAD

**Issue by mguy-usgs** [GSA/code-gov-web#281]
In the US Geological Survey, under the Department of Interior, we are required to add disclaimer text to our source code, same as licenses, we have two "canned" disclaimer options, pasted below as an example. It would be great to have an optional element for Disclaimer Text. Sometimes licenses and disclaimers go hand and hand as is described for GNU (https://www.gnu.org/software/gnusound/Documentation/ar01s08.html). 

1. "This software has been approved for release by the U.S. Geological Survey (USGS). Although the software has been subjected to rigorous review, the USGS reserves the right to update the software as needed pursuant to further analysis and review. No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. Furthermore, the software is released on condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from its authorized or unauthorized use."

2. "This software is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The software has not received final approval by the U.S. Geological Survey (USGS). No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. The software is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the software."

**Comment by iadgovuser1** [comment]
Or a DisclaimerURL similar to LicenseURL. Probably need support for multiple disclaimers too.

**Comment by DanielJDufour** [comment]
Thanks for the input.  We'll discuss when we have our next schema upgrade.  Unfortunately, that could be for a while because we don't want to change the schema too often.

**Comment by DanielJDufour** [comment]
Actually, just double checked the schema and disclaimerURL and disclaimerText are included.  Thus, closing this issue.

**Comment by DanielJDufour** [comment]
You can see current schema here: https://code.gov/#/policy-guide/docs/compliance/inventory-code
