### ISSUE TITLE
How to add CDC projects to browse code?

### ISSUE THREAD

**Issue by leebrian** [GSA/code-gov-web#283]
Hello there, not sure if this is the right place to ask this question, if not please point me in the right direction and I'll redirect.

You have quite a few projects from [HHS](https://code.gov/#/explore-code/agencies/HHS)n the browse by agency portion of your site, but none from the Centers for Disease Control and Prevention. CDC is developing a few open source projects (some at https://github.com/CDCgov/) and I would like to know how to get our projects included in your index.

**Comment by katucker** [comment]
@leebrian, HHS is working on a process for expanding and maintaining the source code inventory but that process is not yet in operational use. If you're anxious to get the CDC source code repositories listed in the inventory, you can either send the metadata for them to ServiceDesk.OCIO.HHS.OS@hhs.gov or edit the file at https://www.hhs.gov/code.json to add your organization's entries and send the updated file to the Service Desk e-mail address.

**Comment by jonheller1** [comment]
@katucker Are you able to modify https://www.hhs.gov/code.json?  The email address in that file didn't work for me and is slightly different than the one you posted.  Thanks.

**Comment by jcastle** [comment]
Closing this as communication looks to be internal.  We are looking to update Code.gov in the future to display sub-agencies and this is based on agency json file.  So CDC should be included in larger HHS json file for posting to hhs.gov/code.json and for harvesting to Code.gov.
