### ISSUE TITLE
Link to Clinger Cohen Act agency list?

### ISSUE THREAD

**Issue by IanLee1521** [GSA/code-gov-web#295]
Would it be reasonable to add a link to the list of Clinger Cohen Act agency acronyms? This is mentioned on the `agency` field on: https://code.gov/#/policy-guide/docs/compliance/inventory-code

and I believe is controlled here:

https://github.com/presidential-innovation-fellows/code-gov-web/blob/2804b87f62d2eff34ed486456cd079dae9713ff1/src/app/components/policy-guide/docs/compliance/compliance-inventory-code/compliance-inventory-code.template.html#L47

**Comment by jcastle** [comment]
I believe you mean the Chief Financial Officer's (CFO) Act agencies.  These are usually the agencies responsible for implementing executive-level policies.  There are 24 major agencies.

**Comment by jcastle** [comment]
The CCA calls at CFO Act agencies.  The list is here https://cfo.gov/about/.
