### ISSUE TITLE
Remove Travis from project / build

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#312]
# Why

Travis is no longer cleared for use within our environments. We should either remove Travis all together or have it not be part of the project's integrations in Github.

I think removing the integration would be the best option.

**Comment by DanielJDufour** [comment]
I'll do it.

**Comment by DanielJDufour** [comment]
I'm closing issue. I deleted .travis.yml, but it's still saved in Git History if anyone every needs to look back at it.
See PR here: https://github.com/GSA/code-gov-web/pull/406
