### ISSUE TITLE
Schema discrepancy - keys for relatedCode

### ISSUE THREAD

**Issue by brockfanning** [GSA/code-gov-web#315]
There is a discrepancy in the keys for "relatedCode", as described [here](https://github.com/presidential-innovation-fellows/code-gov-web/blob/406f91330fa5760f84c06ad08a83d7dd40681a93/src/app/components/policy-guide/docs/compliance/compliance-inventory-code/compliance-inventory-code.template.html#L140) and [here](https://github.com/presidential-innovation-fellows/code-gov-web/blob/9b62ab3276e489726b8ea64b6e5d3870e954eec8/src/assets/schemas/2.0.0.json#L193).

I'm happy to submit a pull request, but I'm not 100% sure which is right. I would assume that the 2.0.0.json file is right - and if anyone could confirm that, I'll put up a PR.

**Comment by DanielJDufour** [comment]
Thanks @brockfanning .  We'll look into this.

**Comment by DanielJDufour** [comment]
We're now directly pulling from our code.json schema file when building our viewer of the code.json schema, so this should no longer be a problem.

We're using this `<json-schema>` web component to build the code.json schema viewer: https://github.com/GSA/json-schema-web-component

And you can view the schema viewer in production here: https://code.gov/about/compliance/inventory-code

Thanks :-)
