### ISSUE TITLE
EPA.gov: Metadata Schema v2.0.0 and New Metadata Tool - NOT WORKING!!!

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#329]
[EPA Submission]

Our code is not making it to the http://code.gov site. The site [code.gov] is displaying the original test file, not the one we make available every day.
Please check.
Thanks.

**Comment by RicardoAReyes** [comment]
[Response]

Thank you for notifying us on this matter. We are reviewing our services to ensure that we are ingesting your new and most current code.json file from the EPA.gov website. 

Notice that www.epa.gov/code.json redirects to the following URL: 

https://www.epa.gov/sites/production/files/buckeye_symlinks/digital_strategy_2017/code.json

If that is incorrect, please let us know where you have placed your most current code.json file?

**Comment by jcastle** [comment]
New JSON file loaded to EPA root and Code.gov.

**Comment by froi** [comment]
@jcastle What do you mean it was loaded to Code.gov?

**Comment by zachary-kuhn** [comment]
I ran the harvester and deployed the new releases to the site. They should now have 88 repositories listed!
