### ISSUE TITLE
Include the Source Code Policy in the site

### ISSUE THREAD

**Issue by mattbailey0** [GSA/code-gov-web#33]
- deprecate sourcecode.cio.gov
- include the policy content in code.gov
- work with community to move related discussion (i.e. on sourcecode.cio.gov issues) to this repository and related channels
- redirect/deprecation notice on sourcecode.cio.gov for any current users.

**Comment by jbjonesjr** [comment]
relevant: [18F's suggestions](https://pages.18f.gov/open-source-guide/writing-the-repo-description/) for best way to deprecate a project


> ### If a project isn’t active, make that clear
> If your repo is not in active development, it’s helpful to let users know this so they don’t make contributions to a non-active repository. We suggest adding the word DEPRECATED before your repo description. Here is an [example](https://github.com/18F/Mario) of a deprecated repo.

**Comment by okamanda** [comment]
@mattbailey0 Is this still a to-do or has your thinking changed?

**Comment by froi** [comment]
The source code policy was added to the site. [You can read it here](https://code.gov/#/policy-guide/policy/introduction).

**Comment by froi** [comment]
The following will be added to our brainstorming topics:

- deprecate sourcecode.cio.gov
- work with community to move related discussion (i.e. on sourcecode.cio.gov issues) to this repository and related channels
- redirect/deprecation notice on sourcecode.cio.gov for any current users.
