### ISSUE TITLE
Code.gov Homepage Load time is too long. Performance Improvement. 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#332]
The new Code.gov Homepage exceeded 18s on load time. DOM loads content in 9.83s. 

Performance Improvement recommendations: 

- Compress png graphics to network transfer, Akamai CDN only compresses JPG format graphics.  
American Flag (https://staging.code.gov/assets/img/american_flag_1920x1280_gradient.png).
- Utilized the Convert program to reduce image size, not quality. (https://www.imagemagick.org/script/convert.php), (https://developers.google.com/speed/docs/insights/OptimizeImages)
- Implement Google's Speedtest improvement recommendation on JS, CSS, Compression, etc.  (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fstaging.code.gov&tab=desktop) 

 
<img width="1436" alt="screen shot 2017-10-20 at 2 30 37 pm" src="https://user-images.githubusercontent.com/2433138/31837229-0bd4227c-b5a6-11e7-92ac-59658c958f0c.png">
<img width="1425" alt="screen shot 2017-10-20 at 2 41 13 pm" src="https://user-images.githubusercontent.com/2433138/31837230-0f4ca49c-b5a6-11e7-8ad7-f439999cec36.png">

**Comment by Kthulu120** [comment]
Is this issue still open? @RicardoAReyes

**Comment by DanielJDufour** [comment]
@Kthulu120 , load time is still definitely an issue and we haven't yet implemented many of the changes that Ricardo suggested.  The load time isn't as bad as it was, but I'd like to keep this issue open and reword the title a little.

**Comment by Kthulu120** [comment]
Cool we'll try and send out a PR this afternoon if we have time with a few optimizations we've found

**Comment by DanielJDufour** [comment]
Load time is significantly improved with the rewrite, but there's still some issues and places where we could greatly increase the speed (e.g. image minimization).  If anyone wants to suggest some improvements, please do so here under our new repo: https://github.com/GSA/code-gov-front-end/issues

Thanks again everyone :-)
