### ISSUE TITLE
Code.gov Homepage bootstrap.min.css.map 404 Not Found 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#333]
On Firefox, bootstrap.min.css.map is showing 404 not found. 
https://staging.code.gov/assets/bootstrap.min.css.map

<img width="1384" alt="screen shot 2017-10-20 at 2 27 40 pm" src="https://user-images.githubusercontent.com/2433138/31837438-cda2b634-b5a6-11e7-843f-ef81e1ce1543.png">

**Comment by DanielJDufour** [comment]
This doesn't appear to be an issue anymore.
