### ISSUE TITLE
Delay loading code.gov

### ISSUE THREAD

**Issue by IanLee1521** [GSA/code-gov-web#376]
I'm currently seeing an ~ 2 sec delay loading code.gov in Google Chrome (v63.0.3239.84 on macOS 10.12.6).

![image](https://user-images.githubusercontent.com/828452/34054317-350ece94-e17f-11e7-8664-515c7655acdc.png)

FWIW, this *is* better than what I see in Safari (11.0.2) which is currently not loading and is stuck at the "flag" screen...

![image2](https://user-images.githubusercontent.com/828452/34054376-7bcc79e4-e17f-11e7-94af-8ed0a5499b3e.png)

**Comment by froi** [comment]
Thanks for the issue @IanLee1521. We'll take a look at this and see what could be the issue.

**Comment by DanielJDufour** [comment]
This is one of our top issues.

**Comment by DanielJDufour** [comment]
I'm working on this now.

**Comment by DanielJDufour** [comment]
This should be fixed with the new version in React!
