### ISSUE TITLE
[Suggestion] Add a schedule for code.gov release on the current website

### ISSUE THREAD

**Issue by wmburke** [GSA/code-gov-web#39]
I see that you have the 90 and 120 day due dates in your milestones, but it would be nice for those less-Github savvy to see this info listed on the current homepage.

**Comment by DanielJDufour** [comment]
We decided to use a road map that lists out near-term, mid-term, and long-term.  Hopefully that works for you. If not, please reopen and let's talk.
https://code.gov/#/roadmap
