### ISSUE TITLE
Improve CircleCI build process

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#410]
## Expected Behavior

Build jobs should share created resources to help shorten the overall build time.

## Current Behavior
The current build process is very slow. There are some tasks that are running on every job that could be just run once and shared.

## Possible Solution

- Start using workspace storage and default build jobs in CircleCI.
- Optimize webpack / angular build.

## Context

Build times are taking too long and sometimes really put a halt on workflow.

**Comment by DanielJDufour** [comment]
We won't be fixing this on Angular version (soon to be archived).  We'll make sure CI is better on new version at code-gov-front-end
