### ISSUE TITLE
Truncate Help Wanted issue description to 250 characters

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#412]
## Expected Behavior

Issues displayed on our help wanted area should have their descriptions truncated to 250 characters.

## Current Behavior

Descriptions are displayed as received.

## Possible Solution

Truncate description text after the markdown is interpreted.

## Context

The design of our help wanted area was never meant to display the complete description text of a Github Issue.

**Comment by DanielJDufour** [comment]
Fixed. Will be included in future PR for help-wanted.
