### ISSUE TITLE
Typings is been depreciated 

### ISSUE THREAD

**Issue by BalajiJBcs** [GSA/code-gov-web#419]
Typings is been depreciated and it is used in required npm dependencies on package.json.

Using depreciated dependencies might cause problem and security issues in future.  

https://github.com/typings/typings  

using alternative is suggested for future builds.

**Comment by DanielJDufour** [comment]
@BalajiJBcs , thank you very much.  We'll look into this promptly.  Have a good day.

**Comment by DanielJDufour** [comment]
We'll remove dependency on typings when we upgrade angular, which will probably be in the middle of march.

**Comment by BalajiJBcs** [comment]
That's great
