### ISSUE TITLE
Department of Interior (DoI) missing from the agencies list (agencies.json)

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#429]
The Department of Interior (DoI) is missing from the agencies list.
https://github.com/GSA/code-gov-web/blob/master/src/assets/agencies.json

## Expected Behavior
DoI should appear an option on the browse by projects agency list, even if no releases are represented.
 
Similar to NRC:
https://www.code.gov/#/explore-code/agencies/NRC

## Current Behavior
DoI is not represented on the agencies list.

**Comment by DanielJDufour** [comment]
Thanks @RicardoAReyes !  @froi , could you add DOI to backend, so agencies endpoint returns it? Thanks.

**Comment by RicardoAReyes** [comment]
direction from product management, only agencies with active software releases will be shown on the Browse by Projects agencies list.
