### ISSUE TITLE
URL query string search bug

### ISSUE THREAD

**Issue by SSAgov** [GSA/code-gov-web#448]
## Expected Behavior
Search using the url and get results. 

## Current Behavior
Search using the url and get empty result page, regardless of results

## Steps to Reproduce (for bugs)
1. Enter the following into a url on firefox
https://code.gov/#/search?q=accessi       ZERO results
https://code.gov/#/search?q=access       246 results, none are viewable
https://code.gov/#/search?q=accessible       246 results, none are viewable
2. see "Loading results" and then after a few seconds get a results page like this with NO results visable:
![image](https://user-images.githubusercontent.com/28628385/36451020-aa3c46de-165d-11e8-80d2-7d5b96f14fa1.png)

## Your Environment
Firefox

**Comment by DanielJDufour** [comment]
@SSAgov , thank you for the heads up.  That's definitely a problem!  We wrote code fixing examples 2 and 3 last week and will be deploying this new code to production this evening.  Please see https://github.com/GSA/code-gov-web/pull/446 for reference to how we fixed this.

Example 1, unfortunately, is not fixed.  My understanding of how the search works is that it searches for whole terms, but not partially typed terms.  I'll bring this up with the team and keep you updated on our discussions.  As a background note, we'll be moving to elastic search within the next couple weeks (right now the front-end is using Lunr), so it'll have to be a fix made on github.com/GSA/code-gov-api.

Thanks again and please let us know if you spot any other bugs! :-)

**Comment by froi** [comment]
Things are looking good With the latest push to staging done by @DanielJDufour

https://staging.code.gov/#/search?q=access
![image](https://user-images.githubusercontent.com/1918027/36455895-4987d84a-1670-11e8-8986-b50afa290b40.png)

https://staging.code.gov/#/search?q=accessible
![image](https://user-images.githubusercontent.com/1918027/36455926-6aced62a-1670-11e8-9ee4-58adb5cc6ba4.png)

https://staging.code.gov/#/search?q=accessible
![image](https://user-images.githubusercontent.com/1918027/36455937-7b9aaf1a-1670-11e8-9b0a-a4d092f58b8f.png)

**Comment by DanielJDufour** [comment]
Code.gov has been updated.  Examples 2 and 3 should be fixed.  I'm moving this issue and the remaining example 1 to backlog.  @SSAgov, please let us know if any other full word queries fail and we'll be discussing what to do about partial-word searches. Thank you for your patience.

**Comment by DanielJDufour** [comment]
User account appears to have been deleted
![image](https://user-images.githubusercontent.com/4313463/49469941-c847a280-f7d6-11e8-8ce3-a8a0fb3bcb03.png)

I'm closing this issue.  Not clear that partial-word searching is a high priority for users, but we can bring it up during the next round of usability tests.
