### ISSUE TITLE
HUD project info is missing - Administrative Client Request Response System

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-web#453]
HUD project info for Administrative Client Request Response System isn't loading:

https://code.gov/#/explore-code/agencies/HUD/repos/Administrative%20Client%20Request/Response%20System

**Comment by DanielJDufour** [comment]
@saracope , I'm looking at this now. Good catch!

**Comment by DanielJDufour** [comment]
Problem seems to be the backslash in the repoID throws off the url resolution.  @saracope , you already know, but for anyone who might read this, Angular likes breaking up urls into segments, which is probably being done by the `/` here.  There's two possible solutions:
1) URL Encoding the `/`
    -- pros: makes routing more resilient
   -- cons: makes routing more complicated.  But we're already using a CustomUrlSerializer, so it's probably not adding much marginal complexity
2) Replacing `/` with _ when creating the repoID
    -- pros: we should probably doing this already because it's best practice and will make the url slugs look better
    -- cons: more work, but @froi would best be able to answer this.

IMHO, we should probably do both.  Better to play it safe.  AFAIK, it's not common to have / in the repoID, so I will still prioritize getting the backend API integrated above this.

**Comment by froi** [comment]
I think the issue is that the front-end is using the __name__ property instead of the __repoId__. This is the JSON for that repo in prod:

```json
{
  "name": "Administrative Client Request/Response System",
  "repositoryURL": "",
  "description": "The Administrative Client Request/Response System is an Office of Administrative and Management Services sponsored system that enables a HUD employee to request Administrative services from their desktop computer and have the request routed directly to the service provider.",
  "tags": [
    "D04"
  ],
  "contact": {
    "email": "russell.d.varnado@hud.gov"
  },
  "permissions": {
    "licenses": [{
      "URL": "",
      "name": ""
    }],
    "usageType": "governmentWideReuse",
    "exemptionText": null
  },
  "laborHours": 2,
  "date": {
    "created": "",
    "lastModified": "",
    "metadataLastUpdated": ""
  },
  "vcs": "",
  "disclaimerText": "",
  "disclaimerURL": "",
  "relatedCode": [{
    "name": "",
    "URL": "",
    "isGovernmentRepo": true
  }],
  "reusedCode": [{
    "name": "",
    "URL": ""
  }],
  "agency": {
    "name": "Department of Housing and Urban Development",
    "acronym": "HUD",
    "website": "https://www.hud.gov/",
    "codeUrl": "https://www.hud.gov/code.json",
    "requirements": {
      "agencyWidePolicy": 0.75,
      "openSourceRequirement": 0,
      "inventoryRequirement": 1,
      "schemaFormat": 0.5,
      "overallCompliance": 0.5833333333333334
    },
    "complianceDashboard": true
  },
  "repoID": "hud_administrative_client_request_response_system"
}
```

The capitalization of in the URL is only found in the __name__ property.

**Comment by DanielJDufour** [comment]
Fixed: https://code.gov/projects/hud_administrative_client_request_response_system
![image](https://user-images.githubusercontent.com/4313463/49471377-b405a480-f7da-11e8-83c4-fedc9ec9b48b.png)
