### ISSUE TITLE
Update Link to Repo on Homepage

### ISSUE THREAD

**Issue by pjdufour** [GSA/code-gov-web#464]
No obvious link to this GitHub repo from homepage.

## Expected Behavior
Expect obvious link to GitHub repo so users can easily submit issues or fix typos.

## Current Behavior
[Visit Project Page](https://github.com/presidential-innovation-fellows/code-gov-web) (which links to old PIF url).

## Possible Solution
[Edit this Page](https://github.com/presidential-innovation-fellows/code-gov-web) or [Submit an Issue](https://github.com/presidential-innovation-fellows/code-gov-web/issues)

**Comment by DanielJDufour** [comment]
Fixed
