### ISSUE TITLE
Search By Language

### ISSUE THREAD

**Issue by pjdufour** [GSA/code-gov-web#465]
I'm interested in seeing which USG entities are using [Go](https://golang.org/) (aka Golang) as it is growing fast.

## Expected Behavior
Show all Go repos 

## Current Behavior
Cannot search by programming language

## Possible Solution
No specific solution in mind

**Comment by froi** [comment]
Hi @pjdufour !

This is something that we have on our radar. We're currently finishing up our "near term" [roadmap tasks](https://code.gov/#/roadmap) and will regroup in the next couple of weeks to go over our features backlog.

Our API currently lets you filter the `/repo` endpoint by language.

Eg.

```
https://api.code.gov/repos?languages=Go
```

For more info on how to use our API please take a look at our [developers page](https://developers.code.gov).

You can also take a look at our API repo and post any issue to it: [code-gov-api](https://github.com/GSA/code-gov-api).

**Comment by DanielJDufour** [comment]
You can now do this. Try: https://code.gov/browse-projects?&languages=Go&page=1&size=10&sort=data_quality
