### ISSUE TITLE
Search results aren't matching search term

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#475]
## Expected Behavior
When searching for a term the results should be more relevant and if I'm searching for a specific project, that projet should be one of the results.

## Current Behavior
Search results aren't matching what was searched for even though one of the suggestions that the
search box offered was clicked.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
1.Type 'mission control' in search box
2.Select suggested search option 'open mission control technologies (open mct)'

![search_bug_openmct](https://user-images.githubusercontent.com/29412125/36983299-0451b4f4-2060-11e8-907a-ac0902704316.gif)

## Context
Trying to search terms and would expect more relevant results, particularly if there's a project with the exact name of the search term

## Your Environment
* Browser Name and version: Chrome 
* Operating System and version (desktop or mobile): Macbook desktop
* Link to your project: https://code.gov/#/

**Comment by DanielJDufour** [comment]
This issue is related to https://github.com/GSA/code-gov-api/issues/195.  Once the backend API is improved with sorting by relevance, you should see the search results automatically improve here.

**Comment by DanielJDufour** [comment]
Fixed
