### ISSUE TITLE
FAQ Updates

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-web#488]
## Expected Behavior

- [ ] order of questions on top with links should match order of questions with answers below
- [ ] remove tools language
- [ ] remove second "FAQ"

**Comment by ctrimm** [comment]
Just a heads up that these links do not work currently on production or on my local. If I click on any FAQ, I get redirected to [here](https://code.gov/#/faq1) - which is an unknown page (see below for screenshot).

From digging deeper into this anchor tag/id issue, it appears to be an Angular Routing problem which is tracked [here](https://github.com/angular/angular/issues/6595). A potential workaround is [located here](https://stackoverflow.com/questions/36101756/angular2-routing-with-hashtag-to-page-anchor).

<img width="961" alt="screen shot 2018-06-05 at 10 14 32 pm" src="https://user-images.githubusercontent.com/1751160/41016652-e069a244-690d-11e8-9fba-ba4a1dc2fc73.png">

**Comment by DanielJDufour** [comment]
@ctrimm , great catch!  So glad to see that you found a solution for our fragments/hash problem! We're still working on the language for the FAQ's page, but once it's complete, we'll be sure to use the solution you found!  Thanks!

Let me know if I misunderstood the problem!  Thanks for the help!

**Comment by DanielJDufour** [comment]
We currently don't have a FAQs page, so I'm going to close this for now.  I also changed the routing up when we moved the code to React.  We shouldn't have any more broken links.  If you find any, feel free to open up another issue at https://github.com/GSA/code-gov-front-end  Thanks again! :-)
