### ISSUE TITLE
Breadcrumb font size too small

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#496]
## Expected Behavior
Breadcrumb font size should be larger (12px)

## Current Behavior
Breadcrumb font size seems to vary, and is either 11px or 14px

## Possible Solution
Update the styling so the breadcrumb font size is 12px

## Steps to Reproduce (for bugs)

1.  Font size ia 11px here https://code.gov/#/explore-code/agencies/NASA
2. Font size is 14px here https://code.gov/#/help-wanted

![screen shot 2018-03-07 at 3 13 48 pm](https://user-images.githubusercontent.com/29412125/37116825-54af191e-221d-11e8-9cf0-9737c9aabd2c.png)

![screen shot 2018-03-07 at 3 10 53 pm](https://user-images.githubusercontent.com/29412125/37116831-58f220de-221d-11e8-8e00-f221ddc63013.png)

## Context
Its inconsistent

## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Macbook

**Comment by DanielJDufour** [comment]
Good catch.  This has been fixed in the style guide and will be fixed on production once integration of the style guide is completed.  The fix in the style guide is here: https://github.com/GSA/code-gov-style/commit/bec974bc014983ad4305850b414847d425c3eaf5
