### ISSUE TITLE
Privacy Policy footer link changes

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#524]
## Expected Behavior

I expect the link to the privacy policy found in the footer not to change.

## Current Behavior

The link for privacy policy is changing with the route of a selected agency

When in Browse Projects -> Department of Commerce (https://code.gov/#/explore-code/agencies/DOC) the link changes to https://code.gov/#/explore-code/agencies/DOC/%28privacy-policy%29

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1918027/38216322-7afe0154-3698-11e8-92f5-f0565263d288.png">

## Possible Solution

Not sure. Definitely a routing issue.

## Steps to Reproduce (for bugs)
1. Go to https://code.gov/#/explore-code/agencies/DOC
2. Check the __Privacy Policy__ link in the footer.
3. Go to https://code.gov/#/explore-code/agencies/ED
4. Check the __Privacy Policy__ link in the footer. They should be different.

## Context

This came up while scrapping the site to generate our sitemap.xml

**Comment by DanielJDufour** [comment]
Thanks. I know what the issue is.  Need to use absolute array of routes instead of relative string for routing.  Will take about an hour to fix.  Fix should be in production for Tuesday night drop.
