### ISSUE TITLE
Possible JSON schema syntax issue

### ISSUE THREAD

**Issue by iadgovuser1** [GSA/code-gov-web#529]
I had an issue with the current schema definition at https://github.com/GSA/code-gov-web/blob/master/src/assets/schemas/2.0.0.json where it wouldn't validate a file by default. I had to change:

- `"required": "licenses"` to `"required": ["licenses"]` (line 106)
- `"required": "email"` to `"required": ["email"],` (line 139) 

Once that change was made then I could validate files without error. The library I'm using to validate is https://www.newtonsoft.com/jsonschema so maybe that's the issue, but I don't know enough about JSON schemas to be sure so wanted to mention it being a possible issue. I came across this when developing https://github.com/iadgov/PSCodeGov

**Comment by DanielJDufour** [comment]
Thanks for the catch! We're looking into this now.

**Comment by DanielJDufour** [comment]
@iadgovuser1 , could you share the code.json file that was failing validation?
