### ISSUE TITLE
'Visit Repo' link goes to organization page on GitHub and not repo page

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#531]
## Expected Behavior
Clicking on Visit Repo link should take me to project repo

## Current Behavior
Clicking Visit Repo takes me to organization page instead of repo page

## Possible Solution
I think this may be an issue with that data in the code.json file, but not certain

## Steps to Reproduce (for bugs)
Visit https://code.gov/#/explore-code/agencies/EPA/repos/epa_usepa_arcgis_api_for_javascript and click on Visit Repo button

**Comment by DanielJDufour** [comment]
ArcGIS API for JavaScript is **not** open source.  The entry in the code.json provided by EPA redirected from epa.go/code.json is incorrect.

![image](https://user-images.githubusercontent.com/4313463/39712220-3b906cd2-51f0-11e8-8e13-bda53f6176d2.png)

See https://developers.arcgis.com/javascript/latest/guide/faq/
![image](https://user-images.githubusercontent.com/4313463/39712286-7ea43846-51f0-11e8-9062-4de56f0b80d8.png)

In general, ESRI products are not open source although there are some exceptions.
