### ISSUE TITLE
Number of Projects in the Browse By Agency Agency Page is pushing text in a weird way.

### ISSUE THREAD

**Issue by rebel-one** [GSA/code-gov-web#542]
Go to https://code.gov/#/explore-code/agencies/SBA

Note that the text: `<p _ngcontent-c20="" class="repos-count"> 5 Projects` is pushing the name of the project to the right a bit. This looks correct on Firefox and Chrome, but not right on Safari. 
<img width="575" alt="screen shot 2018-04-19 at 10 21 37 am" src="https://user-images.githubusercontent.com/25063476/38997510-98e5098a-43bb-11e8-99f7-2eaaffaf7a04.png">
<img width="522" alt="screen shot 2018-04-19 at 10 21 26 am" src="https://user-images.githubusercontent.com/25063476/38997511-98f41632-43bb-11e8-921b-93f88311c52c.png">

**Comment by froi** [comment]
Thanks for the heads up @rebel-one. We’ll be looking at it soon.

**Comment by DanielJDufour** [comment]
I looked at this a little more.  I believe the discrepancy has to do with inconsistency in the order in which Angular and the Browsers render the content.  Browsers often position things based on the position of previous tags/elements.  If a tag appears after having already rendered the subsequent tag, the browser might not properly update everything else.  The solution is to come up with stronger more resilient CSS rules that have fallback capabilities in case one rule fails.

**Comment by DanielJDufour** [comment]
Fixed when changed codebase to React:
![image](https://user-images.githubusercontent.com/4313463/49469410-72262f80-f7d5-11e8-8bbf-360feff56540.png)
