### ISSUE TITLE
As a government employee, I want to know what licenses are being used in government

### ISSUE THREAD

**Issue by afeld** [GSA/code-gov-web#543]
## Expected Behavior

It would be helpful to know:

1. What licenses have been deemed appropriate for use at various government agencies (as documentation), and/or
1. Showing what's actually being used in practice (as a report)

## Current Behavior

None.

## Possible Solution

For 1: There have been a bunch of roundtable conversations with representatives from different agencies, so we might be able to pull this information from notes.

For 2: [github.com identifies known open source licenses for repositories, and has code and an API available for doing that identification.](https://blog.github.com/2015-03-09-open-source-license-usage-on-github-com/) cc @benbalter @jbjonesjr

## Steps to Reproduce (for bugs)

n/a

## Context

There is a lot of consternation at agencies about what open source license they should use. There is a lot of power in being able to point to "here's what other agencies are doing", and thus having strength (from legal concern) in numbers.

## Your Environment

n/a

**Comment by RicardoAReyes** [comment]
@afeld Thank you documenting the question from our work session today. 

@froi can help us identify this dataset from our indexed open source code repositories.

**Comment by DanielJDufour** [comment]
Hi again @afeld !  This is a great question.  I wrote two quick Observable HQ notebooks which provide some insight into what currently exists on code.gov while acknowledging this isn't the complete picture.
 - Chart of Top 10 Licenses on Code.gov: https://beta.observablehq.com/@danieljdufour/licenses-of-projects-on-code-gov
 - Downloadable CSV of Licenses on Code.gov: https://beta.observablehq.com/@danieljdufour/csv-of-licenses-of-projects-on-code-gov

* Note: There's some obvious deduplication of licenses needed.  For example, `CCO` and `Creative Commons Zero (CCO)` are listed as separate licenses. 
* Note: This is only what is currently on code.gov.

I hope this helps.  Happy to discuss more.

Have a great weekend everyone.

**Comment by DanielJDufour** [comment]
I just noticed that the repos endpoint was only returning 3k of the 4k+ repos indexed by code.gov.  We're working on fixing this now and I'll post here when that's done.

**Comment by afeld** [comment]
Sorry for the slow response - this is great! Closing the issue for now, though might be interesting to surface a chart like that on code.gov.

**Comment by DanielJDufour** [comment]
@afeld, we're in discussions internally about how to improve the home page.  I'll make sure to include this in that discussion. Thanks!
