### ISSUE TITLE
Scrub null json fields during harvesting

### ISSUE THREAD

**Issue by USDOJ-FSCP** [GSA/code-gov-web#560]
At DOJ we are using a SharePoint solution that is not feature-rich when it comes to character level text processing. We are collecting code.json entries using an embedded forms feature in SharePoint, but we have limited ability to do anything that SharePoint doesn't provide some sort of plug in for. There is no readily available scripting tool within our reach to manage logic. 

Because of that we have allocated a certain number of fields to various array values like keyword, language and so forth. So we have room on the UI for up to 5 keywords, and if a user only fills three of those blanks, the json file will have two null fields  (,"") .  This causes the harvester to post blank values, little null icons where the key words would be displayed. Its my thinking that a smarter harvester, one that discards null fields, would be a better investment than 10 - 15 improved json generating tools across the government that all will need to have logic that strips null fields.

**Comment by RicardoAReyes** [comment]
Thank you @USDOJ-FSCP for posting the issue.

**Comment by froi** [comment]
Thanks for posting this feedback @USDOJ-FSCP. 

This issue should live in [GSA/code-gov-api](https://github.com/gsa/code-gov-api). I've create the issue [https://github.com/GSA/code-gov-api/issues/220](https://github.com/GSA/code-gov-api/issues/220) to address this. 

This issue will be closed.

**Comment by USDOJ-FSCP** [comment]
Thanks Froilan.

David Landeck
Service Engineering Staff
US Dept. of Justice
202.305.3188 (o)
703.507.2001 (c)
david.landeck@usdoj.gov
