### ISSUE TITLE
Sort "Help Wanted" filters

### ISSUE THREAD

**Issue by tylerbmcsilva** [GSA/code-gov-web#563]
May not so much be a bug, but more of a feature request. I noticed when browsing the [help wanted](https://code.gov/#/help-wanted) tasks that filters were sorted in descending order by how many of each type their was. 

At first this isn't clear, and looks like a random sort (Ex. Intermediate, Advanced, Beginner), but once I looked at the code it was clear that it was sorted by how many of each type.

2 Possible solutions to this issue:
1. Sort them in ascending order by difficulty/size of task (i.e. Small, Medium, Large OR Beginner, Intermediate, Advanced
2. Add the number of projects in parentheses after each filter to show the number of projects in each, and give some order to how they are sorted.

**Comment by DanielJDufour** [comment]
Thanks for the comment.  We definitely need to be more intentional with the ordering of the sub-categories. I like the idea of saying the number of tasks in parentheses.  We'll discuss this as a team and update this ticket when we figured out our way forward.  Thanks again!

**Comment by DanielJDufour** [comment]
Hi, @tylerbmcsilva .  We completely rewrote our frontend in a new repo, which you can find at https://github.com/GSA/code-gov-front-end.  You can also view the new filters here: http://code.gov/open-tasks

I believe we addressed your issue, but feel free to open up a new issue on https://github.com/GSA/code-gov-front-end is there's still an issue.  Thanks! :-)
