### ISSUE TITLE
Schema Validation as a service

### ISSUE THREAD

**Issue by arichiv** [GSA/code-gov-web#564]
It would be nice to have schema validation as a service. https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema provides a GUI, but a CLI interface would be great for automating our deployment system (to ensure our JSON is valid).

One possible interface:

https://api.code.gov/validate-schema&version=2.0.0&uri=https://...
Can return a 200 with no errors, or a 400 with a JSON list of errors

**Comment by arichiv** [comment]
I'd be happy to take a stab at it too, either way :-)

**Comment by froi** [comment]
Also, @arichiv I have no issues with you taking a stab at it. 😄

**Comment by arichiv** [comment]
I can't see that repo :-(

**Comment by froi** [comment]
I wrote the link wrong. Sorry about that, please try the link again.

**Comment by arichiv** [comment]
https://github.com/GSA/code-gov-api/issues/225
