### ISSUE TITLE
Code.gov Compliance Dashboard | Department of State - Missing Data

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#566]
@DanielJDufour and @froi the Compliance Dashboard is missing data for the Department of State.

Compliance Dashboard is only showing status, and the three requirements are missing. 
https://files.fm/u/rc7g6j6p#/view/Screen+Shot+2018-05-31+at+2.11.08+PM.png

However, the code-gov-api agency_metadata.json file has information correctly. 
https://github.com/GSA/code-gov-api/blob/master/config/agency_metadata.json
{
    "id": 12,
    "name": "Department of State",
    "acronym": "DOS",
    "website": "https://state.gov/",
    "codeUrl": "https://www.state.gov/code.json",
    "fallback_file": "DOS.json",
    "requirements": {
      "agencyWidePolicy": 0,
      "openSourceRequirement": 0,
      "inventoryRequirement": 0,
      "schemaFormat": 0.5,
      "overallCompliance": 0
    },
    "complianceDashboard": true
  },

**Comment by froi** [comment]
This is a bug in the API. I'm closing this issue and creating it in [https://github.com/gsa/code-gov-api](https://github.com/gsa/code-gov-api)
