### ISSUE TITLE
Navbar errors on Staging with Firefox

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#573]
There are some errors when testing the new nav on our staging environment. They only appear on Firefox, which makes me think the errors show up on non webkit browsers.

## Firefox

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1918027/41325204-1c2513d0-6e87-11e8-986b-d8b3e29474ab.png">

## Chrome

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1918027/41325217-2ecc6ec0-6e87-11e8-8fac-1e1b4a537c5d.png">

## Sarafi

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1918027/41325767-0fb072d6-6e8a-11e8-94e4-7b7402e30ee4.png">

## Expected Behaviour

The nav should work on all browsers as it's working on Chrome and Safari.

## Possible Solution

I don't have one.

## System

OS: macOS High Sierra v10.13.5
Browsers:

* Firefox Quantum 60.0.2 (64-bit)
* Safari Version 11.1.1 (13605.2.8)
* Chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by DanielJDufour** [comment]
Great catch!

**Comment by DanielJDufour** [comment]
This has been fixed in the code, but I haven't deployed to staging yet.
