### ISSUE TITLE
Menu Navigation | Developers > Notebooks

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#581]
The Menu Navigation option Developer > Notebooks does not load on Chrome browsers.  

The hyperlink should open:
https://beta.observablehq.com/search?query=%22code.gov%22

System Technical Details - OS:
macOS Sierra v. 10.12.6

Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

The navigation works fine on Safari and Firefox. 

See screen capture:
https://postimg.cc/image/o4p68p4pp/

**Comment by DanielJDufour** [comment]
@RicardoAReyes , thank you for catching this!  I'm going to let the ObservableHQ team know.  Could you pop open the developer tools and take a screenshot? I'm hoping you'll see a error appearing in the console in red.

**Comment by froi** [comment]
Hold up. The link is loading for me with some font errors. No idea why it's not loading for @RicardoAReyes 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/1918027/41603562-3b6176de-73ab-11e8-84e9-2076612c905e.png)

Chrome:
Version 67.0.3396.87 (Official Build) (64-bit)

MacOs:
![image](https://user-images.githubusercontent.com/1918027/41603615-5a610284-73ab-11e8-9aef-f639268141ce.png)

**Comment by DanielJDufour** [comment]
Issue was with a user configuration or plugin disabling CORS requests to subdomains.
