### ISSUE TITLE
Code.gov Metadata code.json Generator/Scraper Tools

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#586]
Since the release of the OMB M-16-21 Federal Source Code Policy (FSCP), the U.S. Government (CFO Act agencies) have been focused on completing a comprehensive inventory of their custom developed software from August 2016. Additionally, the Federal agencies have to identify which of those projects have been open sourced, government wide reuse or exempt to comply with the OMB M-16-21 FSCP. For a full list of requirements please see the Metadata Schema 2.0.0 requirements. 

**Code.gov Metadata Schema 2.0.0 Requirements**
https://code.gov/#/policy-guide/docs/compliance/inventory-code

The Code.gov program and U.S. Government would like to developed a code.json generator/scraper tool that would support all GIT version control systems (vcs) to capture the software inventory systematically. The main objective is to reduce the manual process, increase efficiency, reduce human error, and standardize the technical solution. To accomplish these objectives we would like to setup an ongoing working group from the Federal agencies and Open Source Community to support the implementation of the code.json generator/scraper tool(s).

Presently, four (4) Federal agencies have developed their respective code.json generator/scraper tools. The Federal agencies involved are:
**DOE-LLNL** (@IanLee1521)
**DOI-USGS** (@emartinez-usgs)
**GSA-18F** (@jfredrickson5)
**CFPB** (@contolini)

Also, **SSA** (@SSAgov) is evaluating existing options and would like to write a tool that supports BitBucket. 

Four (4) code.json generator/scraper tools have been developed to support GIT base technology version control systems (vcs) like GitHub, BitBucket, and GitLab. However, all the four tools support GitHub.com (Jamie, Dave), only the USGS code.json generator tool supports GitLab, and none of the tools support BitBucket. 

Clearly there is a limitation on these tools. We would like to standardize the API, configuration,  and increase coverage of GIT version controls systems (BitBucket, GitLabs), determine prefer programming language (Python, NodeJS, Ruby), increase adoption from all Federal agencies, and increase collaboration. 

**Current Code-JSON Generator/Scraper Tools:**

1. **Scraper** | https://github.com/LLNL/scraper
Agency: DOE-LLNL
Lead Developer: Ian Lee  - @IanLee1521 
Programming Language: Python
Supports: GitHub
GitHub API:  REST API v3 

2.   **Code-JSON Generator** | https://github.com/usgs/code-json-generator
Agency:  DOI-USGS
Lead Developer: Eric Martinez - @emartinez-usgs
Programming language: NodeJS
Supports: GitHub, GitLab
GitHub API: REST API v3

3.    **Code Inventory** | https://github.com/GSA/codeinventory-github
Agency: GSA-18F
Lead Developer: Jeff Fredrickson
Programming language: Ruby - @jfredrickson5
Supports: GitHub
GitHub API: REST API v3

4.   **Code-Inventory Generator** | https://github.com/cfpb/code-inventory-generator
Agency: CFPB 
Lead Developer: Scott Cranfill - @contolini
Programming language: Ruby
Supports: GitHub
GitHub API: GraphQL API v4

**GItHub API Usage Summary**
**REST API v3** | https://developer.github.com/v3/
DOE Scraper
USGS Code-JSON Generator
GSA Code Inventory

**GraphQL API v4** | https://developer.github.com/v4/
CFPB Code Inventory Generator

**Additional GIT vcs platforms:**
https://bitbucket.org
https://about.gitlab.com

**Comment by RicardoAReyes** [comment]
Last Work Session Meeting Minutes from June 19th, 2018.

Today's work session on the software inventory generators/scrapers discussion. We addressed each of the software tools that have been developed, identified limitations on each of the tools (i.e. lack of documentation, the solutions do not support all major GIT platforms (BitBucket, GitLabs, GitHub), we determined some of the challenges with the labor hour estimates through code using the (CLOC + COCOMO II model), lack of software reuse/adoption, and plan future collaborations. 

Also, we learned about Jeff Fredrickson (GSA) plans to build a NodeJS component called code-clerk. All these discussion points enforces our plans to have more frequent engagements and collaboration. 

Action Items:

1. Create a Slack channel with GSA for direct communication / collaboration.

		Scott, Eric, and Chris should have received email access request. [Please confirm]
		Ian already has access. 
    	Upon registration, you should have access to code-gov-partners channel. 
    	
2. Eric to followup with Ian to discuss GitLab integration on Scraper tool.

		Eric to setup Ian's USGS GitLab account.
		Ian to validate scraper tool. 

3. Ricardo to capture/document business needs, requirements and use cases from agencies on software inventory generators/scrapers.

		Document GitHub issues. 

4. Normalize the tools through team collaboration. 

		Standardize the API, configuration and large coverage of GIT version controls systems. 
		Determine prefer programming language (Python, NodeJS, Ruby).
		Increase adoption from all Federal agencies
		Increase collaboration



5. Integrated labor hour estimated calculation into current tools. 

		Leverage LLNL's [Scraper Tool Approach](https://github.com/LLNL/scraper/blob/master/scraper/code_gov/__init__.py#L197, "")
		Joe to present Labor Hour Calculation Instructions to all working group members.

6. Joe/Ricardo to follow up with USC.edu on API implementation request for COCOMO II service. 
		
		[http://csse.usc.edu/tools/cocomoii.php](http://csse.usc.edu/tools/cocomoii.php)

**Comment by RicardoAReyes** [comment]
Posting response from @emartinez-usgs: 

Great talk yesterday. To follow-up on my action items:

1.  I have joined the gsa-tts slack host and the #code-gov-partners channel. I'm not sure if there is a more appropriate place for us to collaborate?

2. I've set @IanLee1521 up with an account on the USGS GitLab (https://code.usgs.gov/) for development and testing purposes.

3. I've updated the documentation on the code-json-generator project (Node) to hopefully make the project more useful. Can somebody look to see if the documentation seems reasonable for a new user to get started?

**Comment by RicardoAReyes** [comment]
Posting response from @jfredrickson5 

Clarifications on the GSA tools:

**CodeInventory tool:**
- The tool (CodeInventory) is a Ruby gem: (https://github.com/GSA/codeinventory)
- It's actually a core tool that provides basic functionality in a CLI and API, and it can be extended via plugins (which are also gems) to support any type of repository
- One plugin we developed is to add GitHub support: (https://github.com/GSA/codeinventory-github)

New Code Clerk tool (started a couple of weeks ago):
- (https://github.com/GSA/code-clerk)
- Designed more as an API/SDK, which can power a CLI tool (it does have a basic CLI included)
- Designed to be extensible: the user can very finely customize how they want to transform their repository metadata into code.json, but it also comes with easy defaults
- Node is more commonly used in web app projects these days, hence the transition to a new language
- Only supports GitHub right now, hard coded, with the intention to make it modular and support any repository

I'm looking forward to working with everyone on Slack to focus our collective efforts!

We can discuss in more detail once we all get on Slack, but some thoughts:
- How many of you only need a CLI tool? How many want the tool to provide an API/SDK?
- By what means should a tool be extensible, and how extensible should it be? Every agency does things differently. What kind of flexibility will everyone need?
- If you really have to use SLOC+COCOMO, consider implementing the formula in a reusable open source library, rather than relying on an external service.

**Comment by jfredrickson5** [comment]
@RicardoAReyes what's the status on getting everyone in Slack? Do we have a specific channel yet? Looking forward to starting on some collaboration there.

**Comment by jfredrickson5** [comment]
@RicardoAReyes could you shoot me an invite, please?

**Comment by RicardoAReyes** [comment]
I have submitted your access request, you should get an email invitation today or tomorrow at the latest.

**Comment by katucker** [comment]
Adding information for an HHS planned application.

Source-Code-Inventory | https://github.com/HHS/Source-Code-Inventory
Agency: HHS
Lead Developer: TBD
Programming Language: Javascript
Supports: GitHub, GitLab, others
GitHub API: TBD

The basic concept is to add some capabilities to the existing code.json generators, specifically to enable managing metadata for offline repositories (i.e., repos that can't be directly queried by the source code inventory application), and to provide a UI for adjudicating which repos to actually include in the published code.json file.

The proposed implementation uses a GitHub repository and its associated wiki and GitHub Pages website. Entries for the source code inventory are recorded in wiki pages. Client-side Javascript is served through the GitHub Pages site to support proposing entries manually, defining "libraries" of repositories such as GitHub organization accounts that can be queried for automatically proposing entries, reviewing proposed entries, and generating an updated code.json file.

Features proposed for the application and design ideas are documented in the [Issues log](https://github.com/HHS/Source-Code-Inventory/issues). The repository's [wiki](https://github.com/HHS/Source-Code-Inventory/wiki) shows a mockup of the inventory representation as individual wiki pages.

**Comment by RicardoAReyes** [comment]
Documentation has been moved to a GitHub Markdown file.

Please see documentation here: 
https://github.com/GSA/code-gov/blob/master/CODE_JSON_GENERATORS.md

Add issues, action items, system requirements to this project:
https://github.com/GSA/code-gov/projects/1
