### ISSUE TITLE
Walkoff not showing up on site

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#603]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
When I click on View Project under Walkoff on homepage I expect to be taken to the project details page.  Also, if I search for Walkoff I expect to see a result

## Current Behavior

Clicking the link takes me to a blank page, and if I try searching for Walkoff I don't get any results

## Possible Solution

Don't know

## Steps to Reproduce (for bugs)

1. Click on View Project under Walkoff on homepage
2. Try searching for Walkoff

## Context

Walkoff is no longer on the site

## Your Environment

* Version used:
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): MacBook Pro High Sierra
* Link to your project: https://code.gov/#/explore-code/agencies/NSA/repos/nsa_walkoff

**Comment by DanielJDufour** [comment]
featured projects are configured in code-gov-config.json (which is a symbolic link to code-dot-gov.json). lemme know if that doesn't fix it

**Comment by froi** [comment]
This is a backend issue. The fallback file for NSA was deleted. I'll be working on it in the [code-gov-api](https://github.com/gsa/code-gov-api) repo
