### ISSUE TITLE
Upgrade vulnerable dependencies

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#610]
## Expected Behavior
Project dependencies should not have vulnarabilities.

## Current Behavior
A number of dependencies are being marked as vulnerable.

## Possible Solution
Run `npm audit` and upgrade the vulnerable dependencies.

## Steps to Reproduce (for bugs)
1. `npm audit`

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Security Vulnerabilities identified by npm audit #Sprint_33](https://trello.com/c/p8aJVBFw/817-fix-security-vulnerabilities-identified-by-npm-audit-sprint33)

**Comment by DanielJDufour** [comment]
This is obsolete as front-end is now using code-gov-front-end
