### ISSUE TITLE
Broken link for Help Wanted item: Labor Hours Estimation for Code.gov Open Source Repositories

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-web#629]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Link resolves to correct page

## Current Behavior
Loads a page without the project info

## Steps to Reproduce (for bugs)
<img width="861" alt="screen shot 2018-08-01 at 12 47 41 pm" src="https://user-images.githubusercontent.com/2197515/43536040-95aeedce-9589-11e8-924c-0e919ab257dd.png">
<img width="973" alt="screen shot 2018-08-01 at 12 50 59 pm" src="https://user-images.githubusercontent.com/2197515/43536049-98640e5a-9589-11e8-946c-1f5921999c71.png">

## Your Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by DanielJDufour** [comment]
Thanks for the catch.  I'll take a look!

**Comment by DanielJDufour** [comment]
I did a little diving and it appears that GSA renamed the repo and we weren't able to index it.  @froi , can you take a deeper look and find out for sure what happened?

Here's a screenshot of the relevant repo on gsa.gov/code.json:
![image](https://user-images.githubusercontent.com/4313463/43537381-24f58a76-958d-11e8-987b-6393e153be18.png)

And I couldn't find it in https://api.code.gov/repos?api_key={{API KEY HERE}}&size=100000

**Comment by DanielJDufour** [comment]
Workaround could be just directing project details to code-gov page on code.gov

**Comment by saracope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Help Wanted UI #Sprint_36](https://trello.com/c/LsjlPztO/902-update-help-wanted-ui-sprint36)
