### ISSUE TITLE
New Filter Pagination Reset Issue

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#637]
@DanielJDufour on the new code.gov filter feature looks great. As a new user, I discovered that when a user clicks on the different agency filters which increase or decrease the project results (technically increasing or decreasing the pagination) the pagination # does not reset to 1. 

For example, by default the results show all projects, select CFPB then click on page 5. Then deselect the CFPB, it should results all projects, the pagination stays on page 5.  I was expecting to reset to page 1 - the start of the list. 

From a UX perspective, was the functionally programmed intentionally that way.  If the user resets the filters, should the pagination return back to page 1? or when agency filters change, should the pagination start from page 1? 

![code_gov_filter_pagination_reset](https://user-images.githubusercontent.com/2433138/44219640-98529180-a14a-11e8-844f-0f1e508630b9.gif)

**Comment by DanielJDufour** [comment]
Fixed on code-gov-front-end
