### ISSUE TITLE
"Help Wanted" issues not filtering by "Featured/Active/Popular"

### ISSUE THREAD

**Issue by lbeaufort** [GSA/code-gov-web#638]
Hi there! 👋 I searched open issues and couldn't find this one, sorry if I missed it.

## Expected Behavior
Clicking on the Featured/Active/Popular links should filter the "Help Wanted" issues here: https://code.gov/#/help-wanted
<img width="867" alt="screen shot 2018-08-17 at 10 00 16 am" src="https://user-images.githubusercontent.com/31420082/44270193-baa8e580-a204-11e8-8564-ca02cc4dc840.png">

## Current Behavior
It doesn't look like the filters work. Hovering over the links show that they all link to `href="#"`

## Possible Solution
Not sure how these links are supposed to filter, sorry!

## Steps to Reproduce (for bugs)
1. Go to https://code.gov/#/help-wanted
2. Click on "Featured" 
3. Click on "Active"
4. Click on "Popular"

## Context
I was exploring "Help Wanted" issues

## Your Environment
* Browser Name and version: Chrome on Mac - Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop, Mac OS Sierra 10.12.6

Thanks for taking a look! 🇺🇸

**Comment by saracope** [comment]
Thanks, @lbeaufort! We're working on this fix and will update when it's updated in production.

**Comment by saracope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Help Wanted UI #Sprint_36](https://trello.com/c/LsjlPztO/902-update-help-wanted-ui-sprint36)
