### ISSUE TITLE
Results change in order when I use the Back button on Browser

### ISSUE THREAD

**Issue by TeeMorris** [GSA/code-gov-web#649]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

When I go through projects on Code.gov, I will use Firefox's or Chrome's "Back" button to return to the page I was on. 
## Current Behavior

The problem is when I do so, I go back to "page 1" not the page I was previously on (like Page 3 or Page 4). Also, it appeared the order of projects reshuffled, appearing in a different order than before.
## Steps to Reproduce (for bugs)

1. Go to any agency with multiple pages of projects (i.e. NASA, EPA, GSA)
2. Click to "Page 4" of projects. 
3. Click on a specific project.
4. Use the browser's Back button to return to page of projects.

## Context

As you know, Daniel, I have been working through agencies and building a repository of "practical" applications for us to use at special events. What I'm noticing, though, is when I return to search results, I see a different order as well as I'm back on Page 1. I'm concerned I am missing or skipping other projects that would be worth attention.
## Your Environment

* Version used:
* Browser Name and version: Chrome 
* Operating System and version (desktop or mobile): Mac OS X
* Link to your project:

**Comment by DanielJDufour** [comment]
@jlow81 , thoughts on ideal user experience / page flow here?

**Comment by jlow81** [comment]
@DanielJDufour can we keep track of what page the user is on so if they go back they land on the same page number they were on before?

If the user hits the back button the expectation is they are returned the the previous page and state they were on.

**Comment by DanielJDufour** [comment]
@jlow81 , yes we can do that.  We can do that through a URL param.  For example, if someone searched `water` and went to the second page, their url would look like `https://code.gov/#!/search?q=water&page=2`.  We should also probably do something similar for browse projects where we save the state of the page through url params for example, if someone wanted to view browse projects for python, the url would update to `https://code.gov/#!/browse-projects?language=Python&page=10`.

**Comment by jlow81** [comment]
@DanielJDufour Yes, lets do that

**Comment by DanielJDufour** [comment]
@jlow81 , I created a card for the saving state task, which you can view here: https://trello.com/c/x15bosG9/975-save-state-on-browse-projects-search-results-and-help-wanted

This would be a large effort, so will have to wait till next sprint.

**Comment by DanielJDufour** [comment]
Fixed on code-gov-front-end
