### ISSUE TITLE
Agency breadcrumb not working on repo page

### ISSUE THREAD

**Issue by lbeaufort** [GSA/code-gov-web#657]
Hi! Sorry if this is a known issue - I couldn't find anything about it.

## Expected Behavior
When looking at a repo page like [this one](https://code.gov/#!/explore-code/agencies/NASA/repos/nasa_gsfc_advanced_limage_assessment_system_alias_), clicking on the agency breadcrumb should take the user back to all projects by that agency.

## Current Behavior
When looking at a repo page like [this one](https://code.gov/#!/explore-code/agencies/NASA/repos/nasa_gsfc_advanced_limage_assessment_system_alias_), clicking on the agency breadcrumb takes you to https://code.gov/#!/explore-code/agencies/NASA, which just says "Loading Results" for minutes:

<img width="710" alt="screen shot 2018-09-18 at 7 13 57 pm" src="https://user-images.githubusercontent.com/31420082/45721898-ea3a6d00-bb77-11e8-96bd-dff616185875.png">

<img width="1125" alt="screen shot 2018-09-18 at 7 14 10 pm" src="https://user-images.githubusercontent.com/31420082/45721717-39cc6900-bb77-11e8-8140-07cba077ce08.png">

## Possible Solution
The link could go here instead: https://code.gov/#!/browse-projects?agencies=NASA

## Steps to Reproduce (for bugs)
1. From the home page, search for "ALIAS" or choose NASA in the "browse by agency" dropdown
2. Click on "Advanced Land Image Assessment System (ALIAS)"
3. Click on the "NASA" breadcrumb
4. Results don't load

## Context
I was exploring my agency's repos (https://code.gov/#!/browse-projects?agencies=FEC)

## Your Environment
* Chrome on Mac

Thanks!!
🇺🇸

**Comment by DanielJDufour** [comment]
Great catch! Thanks! We'll definitely take a look tomorrow.

**Comment by saracope** [comment]
This was fixed in production. Closing out. Thanks @lbeaufort!
