### ISSUE TITLE
Count of Tasks does not reflect currently selected filters

### ISSUE THREAD

**Issue by bushidocodes** [GSA/code-gov-web#658]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

When on [the "Help Wanted" view](https://code.gov/#!/help-wanted), I would expect the count "30 Open Tasks" to update depending on the count of items matching the filter state selected in the sidebar.

## Current Behavior

The title is static and unfiltered, and I'm all about the filters.

![](https://media.giphy.com/media/3o6EhJJJnEJqWtw55C/giphy.gif)

## Possible Solution

Recalculate and rerender the title with a template string using the length of the filtered array.

## Steps to Reproduce (for bugs)

1. Go to [the "Help Wanted" view](https://code.gov/#!/help-wanted)
2. Select some filters
3. Observe that the count in the title doesn't change.

## Context

Not a big deal, but helps me understand the breakdown of open issues looking for external contributors.

## Your Environment

* Version used:
* Browser Name and version: Version 68.0.3440.106 (Official Build) (64-bit) 
* Operating System and version (desktop or mobile): macOS High Sierra 10.13.6
* Link to your project: n/a

**Comment by DanielJDufour** [comment]
Thanks for the catch @bushidocodes ! I'll make sure to bring this up with the team and keep you updated via this issue. Thanks!

**Comment by DanielJDufour** [comment]
Fixed on code-gov-front-end
