### ISSUE TITLE
Nav broken

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-web#659]
## Expected Behavior
In the main nav, clicking on an item with a submenu opens that menu.

## Current Behavior
Clicking on an item with a submenu jumps the user back to home.

## Possible Solution
Update the anchor element.

## Steps to Reproduce (for bugs)

1. Click on a nav link without a submenu, ex. Browse Projects (page loads correctly)
2. Click on About (Menu flashes and user is taken back to home)

![nav-bug](https://user-images.githubusercontent.com/2197515/45835487-44524400-bcd8-11e8-921e-706f135f5d3f.gif)

**Comment by DanielJDufour** [comment]
@saracope , I think we should replace the a tags with divs in the top level that open up submenus

**Comment by DanielJDufour** [comment]
@saracope , if you got a fix with anchors though, submit a PR :-)
