### ISSUE TITLE
Issue with agency filter for help wanted

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-web#671]
## Expected Behavior

The agency name is shown.

## Current Behavior

[object Object] is shown

## Steps to Reproduce (for bugs)

1. Navigate to help wanted page
2. Click on show more in the Agency filter
3. View the last entry of [object Object]

<img width="1084" alt="screen shot 2018-10-03 at 9 38 10 am" src="https://user-images.githubusercontent.com/2197515/46414095-5d9fbb00-c6f0-11e8-9df9-3af77b10337e.png">

**Comment by ftonato** [comment]
I'll work on this.
