### ISSUE TITLE
Browse Projects and Search Results on mobile have infinite scroll instead of pagination

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#677]
## Expected Behavior

Browse Projects and Search Results on mobile should have pagination instead of infinite scroll

## Current Behavior

Browse Projects and Search Results on mobile have infinite scroll and if you try to view all projects that list is very long with over 4,000 projects

## Possible Solution

Add pagination to mobile

**Comment by DanielJDufour** [comment]
Fixed
