### ISSUE TITLE
Browse Projects repository count does not reflect filter change

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#680]
The Browser Projects repository count does not change based on user's filter selection. The count is constant and not reflect the end user's filter action. 

URL: https://code.gov/#!/browse-projects

How to replicate:

1. Visit Browse Projects URL: https://code.gov/#!/browse-projects
2. Filter by a Federal Agency, i.e. DOE (https://code.gov/#!/browse-projects?agencies=DOE)
3. Notice that the repository count did not change. 
4. However, the footer pagination repository count did change based on filter selection. 

See attached animation. 

![code_repository_count_error](https://user-images.githubusercontent.com/2433138/46756513-abd73000-cc95-11e8-80ca-40eb39643498.gif)

Agencies have notified the issue and were concerned about the OSS not being indexed on Code.gov

Expectation:
 - Repository count should reflect the number of OSS indexed by that agency based on filter options.

**Comment by froi** [comment]
To give some context to this. I don't think this value is currently being calculated from the result set. It's a value that is provided by the API.

Example diractly from the API:

![screenshot 2018-10-10 23 15 48](https://user-images.githubusercontent.com/1918027/46778630-963c2780-cce2-11e8-9d85-d4bf87c0be73.png)

Here's an example form search results:

![search_results](https://user-images.githubusercontent.com/1918027/46778542-2d54af80-cce2-11e8-9f93-7121247bf988.gif)
