### ISSUE TITLE
Browse Projects repository count is incorrect - includes Exempted repos. 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#682]
The Browser Projects repository count is incorrect. The total count includes exempted repositories which is incorrect. exempted projects should not count towards the total because only OpenSource and GovernmentWideReuse repos are exposed to the public on Code.gov.

URL: https://code.gov/#!/browse-projects

![screen shot 2018-10-12 at 7 59 17 am](https://user-images.githubusercontent.com/2433138/46869582-4d779200-cdfa-11e8-83ff-243debf73ad2.png)

How to replicate:

1. Visit Browse Projects URL: https://code.gov/#!/browse-projects
    Notice that the repository count total, **5237** (Oct 12, 2018). 
2. Under the Usage Type select Open Source.
    Notice the repository count on the footer of the page, **3759**.
3. Deselect Open Source under the Usage Type, and then select Government-Wide Reuse. 
    Notice the repository count on the footer of the page, **1139**. 
4. Adding the Open Source + Government-Wide Reuse totals = **4898**.

![repo-count](https://user-images.githubusercontent.com/2433138/46869545-346ee100-cdfa-11e8-8112-e3a5d19a1cfc.gif)

Expected Result:
 The repository total count should only add the Open Source and Government-Wide Reuse repos.

**Comment by GenevieveFlynn** [comment]
We(Me and @samuelgassman7) investigated the front end and discovered that the API was not filtering correctly meaning that it does not filter by usageType and it returns all of the repositories that have been indexed by the API.

<img width="1136" alt="screen shot 2018-10-13 at 2 47 07 pm" src="https://user-images.githubusercontent.com/43386675/46908924-dd4f3600-cef7-11e8-951e-3f242e61333a.png">

https://api.code.gov/repos?permissions.usageType=opensource&permissions.usageType=governmentwidereuse

**Comment by RicardoAReyes** [comment]
Confirmed that the issue is an API problem with @froi
