### ISSUE TITLE
Project Error Page

### ISSUE THREAD

**Issue by Arjun-Vijay** [GSA/code-gov-web#686]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Upon clicking 'Browse Open Projects' button on the homepage an user should be directed to open projects

## Current Behavior
 Upon clicking the button an error page appears

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saracope** [comment]
This was fixed with #687. Thanks!
