### ISSUE TITLE
Clicking next in pagination should bring user to top of page

### ISSUE THREAD

**Issue by jtumina** [GSA/code-gov-web#690]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

After reaching end of a page on "Browse Projects" section, user should return to top of page.

## Current Behavior

Currently, the user is stuck at the the bottom of the page and not returned to the top.

## Steps to Reproduce (for bugs)

1. Go to "Browse Projects"
2. Scroll to bottom of page 
3. Click "next"

**Comment by DanielJDufour** [comment]
@jtumina , this is a great suggestion.  Thank you!

**Comment by ftonato** [comment]
I'll work on this.
