### ISSUE TITLE
Superscript links on 'Implementation' page return page not found

### ISSUE THREAD

**Issue by lukefretwell** [GSA/code-gov-web#700]
## Expected Behavior
When I click on a superscript link on the implementation page, it should take me to the referring reference.

## Current Behavior
When I click, on the reference number on the [implementation page](https://code.gov/#!/policy-guide/policy/implementation), it returns a page not found.

## Steps to Reproduce (for bugs)
1. Go to https://code.gov/#!/policy-guide/policy/implementation
2. Click on superscript link.
3. Get PNF: Ex: https://code.gov/#!/fn33

**Comment by froi** [comment]
Hi @lukefretwell.

Thanks for the issue. We will start looking into it.

**Comment by DanielJDufour** [comment]
Thanks for catching this.  As this was an issue with the old Angular code, I'm going to close this issue.  However, we still have the issue on the React site (for a different reason), so I created an issue there: https://github.com/GSA/code-gov-front-end/issues/102

Thanks again @lukefretwell !
