### ISSUE TITLE
Number of repos should update with filter

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-web#703]
## Expected Behavior
When filter is engaged the number of repos should update to the the current number of repos being returned

## Current Behavior
Number of repos stays at TOTAL number (currently 4,925)

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
An example...
Browse by Department of Commerce, the number of repos for Commerce is 3 however the number of repos is showing as 4,925.  It should be 3

![num_repos_filter](https://user-images.githubusercontent.com/29412125/47441259-bdccce80-d77d-11e8-8b61-b0a71cd77a01.png)

**Comment by DanielJDufour** [comment]
Fixed
